//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneotomasyonuSe
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_adı { get; set; }
        public string admin_soyad { get; set; }
        public string admin_kullaniciAd { get; set; }
        public string admin_şifre { get; set; }
    }
}
