//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneotomasyonuSe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public int kitap_id { get; set; }
        public string kitap_isim { get; set; }
        public string kitap_yazar { get; set; }
        public string kitap_yayınevi { get; set; }
        public Nullable<int> kitap_sayfasayisi { get; set; }
    }
}
